# Change prefix to Ctrl+a (easier to reach)
unbind C-a
set -g prefix C-b
bind C-b send-prefix

# Enable mouse support
set -g mouse on

# Start window numbering at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1

# Better split keys
bind | split-window -h
bind - split-window -v

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Status bar at top
set-option -g status-position top

# Basic color scheme
# set -g status-bg black
# set -g status-fg white
# set -g window-status-current-style bg=blue,fg=white,bold

### plugin section ###
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'adonespitogo/tmux-tokyo-night'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
