-- Generated by wallust — do not edit (will be overwritten on wallpaper change).
-- Consumed by hyprland.lua via pcall(dofile, ...); falls back to Catppuccin if missing.
return {
    color4 = "{{color4}}",
    color5 = "{{color5}}",
    color8 = "{{color8}}",
}
