gui:
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#6c7086"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  nerdFontsVersion: "3"
  showIcons: true
  mouseEvents: true
  sidePanelWidth: 0.25
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  autoFetch: true
  autoRefresh: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
keybinding:
  universal:
    quit: q
    quit-alt1: <c-c>
