#!/usr/bin/env bash
# apply-brave-theme.sh [scheme] — seed Brave's native theme from the wallpaper palette.
#
#   apply-brave-theme.sh          dark, TonalSpot (default)
#   apply-brave-theme.sh light
#   apply-brave-theme.sh dark vibrant
#
# WHY THIS IS SO MUCH SMALLER THAN EVERYTHING ELSE IN THE RIZZ PIPELINE
#
# This is Brave 154 / Chromium 154. `brave --version` reporting "1.96.59" is the
# Chromium milestone embedded in the version string, not Brave's own version —
# read it wrong and you will hunt for theme features that no longer exist.
#
# M154 DELETED the multi-colour native theme. Verified against the shipped
# binary, not docs:
#   strings /opt/brave-bin/brave | grep -cxF frame_color              -> 0
#   strings /opt/brave-bin/brave | grep -cxF ntp/background_color      -> 0
#   strings /opt/brave-bin/brave | grep -c  'chrome\.theme'            -> 0
# The classic {frame, toolbar, tab_background_text, …} JSON is not parsed, and
# the `chrome.theme` WebExtension API is gone too, so there is no extension
# route either. What remains is ONE ARGB seed colour plus a tone-mapping
# variant; Chromium derives every other surface from it via ui::ColorProvider.
#
# That is a smaller win than the other apps, but the payoff is in the ACCENT,
# not the surfaces — the same conclusion the GTK3 work reached (stock Breeze's
# hardcoded #315bef was the loudest colour in the file manager). A seed colour
# is precisely the part that mattered.
#
# RUN WITH BRAVE CLOSED. PrefService rewrites the entire Preferences file on a
# ~10s debounce and unconditionally on exit, so an edit made while Brave is
# running is silently discarded. This is the one place in the rizz where a
# "did you save?" question has a destructive answer.
set -euo pipefail

SCHEME="${1:-dark}"
VARIANT="${2:-tonalspot}"
PREF="$HOME/.config/BraveSoftware/Brave-Browser/Default/Preferences"
PALETTE="$HOME/.dotfiles/firefox/generated-colors.css"
FALLBACK="$HOME/.dotfiles/firefox/fallback.css"

[ -f "$PREF" ] || { echo "error: no Brave profile at $PREF" >&2; exit 1; }

# ── Refuse to write into a live profile ──────────────────────────────────────
if pgrep -x brave >/dev/null 2>&1; then
    echo "error: Brave is running. Quit it first — Preferences is rewritten on" >&2
    echo "       exit and any change made now will be lost." >&2
    echo "       (see the note in the script header)" >&2
    exit 1
fi

# ── Pull the accent out of the live palette ──────────────────────────────────
# Reuse the Firefox palette rather than running a second generator, so both
# browsers always agree on what "the accent" is.
src="$PALETTE"
[ -f "$src" ] || src="$FALLBACK"
[ -f "$src" ] || { echo "error: no palette found ($PALETTE or $FALLBACK)" >&2; exit 1; }

hex=$(grep -oE -- '--color-accent-primary:[[:space:]]*#[0-9a-fA-F]{6}' "$src" | head -1 | grep -oE '#[0-9a-fA-F]{6}')
[ -n "$hex" ] || { echo "error: no --color-accent-primary in $src" >&2; exit 1; }

# ── Map to the enums ─────────────────────────────────────────────────────────
# PrefService stores colours as SIGNED 32-bit ints. Writing "#7C5CFF" or an
# unsigned value is the single most common reason "I wrote it and nothing
# happened" — the pref is simply ignored, with no error.
case "$SCHEME" in
    dark)  scheme_id=2 ;;   # 0=system 1=light 2=dark
    light) scheme_id=1 ;;
    *) echo "error: scheme must be 'dark' or 'light' (got '$SCHEME')" >&2; exit 1 ;;
esac

case "$VARIANT" in
    system)    variant_id=0 ;;
    tonalspot) variant_id=1 ;;   # the Material 3 default; best general choice
    neutral)   variant_id=2 ;;
    vibrant)   variant_id=3 ;;
    expressive) variant_id=4 ;;
    *) echo "error: variant must be system|tonalspot|neutral|vibrant|expressive" >&2; exit 1 ;;
esac

r=$(( 16#${hex:1:2} )); g=$(( 16#${hex:3:2} )); b=$(( 16#${hex:5:2} ))
argb=$(( (0xFF << 24) | (r << 16) | (g << 8) | b ))
[ "$argb" -ge 2147483648 ] && argb=$(( argb - 4294967296 ))

# ── Write it ─────────────────────────────────────────────────────────────────
# Use the autogenerated_theme_id branch deliberately: it is the only path in
# ThemeService::InitFromPrefs that explicitly calls SwapThemeSupplier(), rather
# than relying on ColorProvider re-resolving later. These prefs are registered
# without SYNCABLE_PREF and this profile has no preference MACs, so a plain
# hand-edit of the JSON is safe — but it is still an unsupported path, which is
# why the colour lands in a file the user can always inspect.
tmp=$(mktemp)
python3 - "$PREF" "$argb" "$scheme_id" "$variant_id" > "$tmp" <<'PY'
import json, sys
path, argb, scheme, variant = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4])
with open(path) as fh:
    prefs = json.load(fh)
prefs["extensions.theme.id"]          = "autogenerated_theme_id"
prefs["autogenerated.theme.color"]    = argb
prefs["browser.theme.color_scheme2"]  = scheme
prefs["browser.theme.color_variant2"] = variant
json.dump(prefs, sys.stdout, separators=(",", ":"))
PY
cat "$tmp" > "$PREF" && rm -f "$tmp"

echo "==> Brave theme: seed $hex (argb $argb), scheme=$SCHEME, variant=$VARIANT"
echo "    Chromium will tone-map this, so the rendered UI will NOT be exactly"
echo "    $hex — that is expected, not a failure."
echo "    Launch Brave and check brave://settings/appearance."
